### ISSUE TITLE
`distance` and `propagate` result in big innacuraccies 

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalBilliards.jl#13]
the [`distance`](https://datseris.github.io/DynamicalBilliards.jl/stable/basic/library/#DynamicalBilliards.distance) function measures the signed distance between particle and obstacle. The [`collisiontime`](https://datseris.github.io/DynamicalBilliards.jl/stable/basic/library/#DynamicalBilliards.collisiontime) function calculates the time until collision with a given obstacle. The function [`propagate!`](https://datseris.github.io/DynamicalBilliards.jl/stable/basic/library/#DynamicalBilliards.propagate!) moves a particle forwards in time.

The basic way the package works is that it first calculates the collision time and then propagates a particle for that amount of time. After that other processes happen (e.g. specular reflection).

The problem is that after the particle is propagated, it should be really close (if not exactly on top) of an obstacle. However, measuring the `distance` between the particle and the obstacle, it can be as large as of order `1e-9`. I think that this is really inaccurate and I cannot understand the reason why. Both the functions `collisiontime` and `distance` are supposed to result in exact answers in the "theoretical sense". How come that the numeric implementation is so far from it?

@dpsanders what do you think? Is it reasonable that after propagation the particle can still be so far away from an obstacle's borders?

**Comment by dpsanders** [comment]
Could you provide example code where this happens, please?

**Comment by Datseris** [comment]
Sure. I am copying one of the functions of the tests folder:
```julia
function check_previous_obstacle(partnum; printinfo = true)
  if printinfo
    println("\nCurrently testing: check_previous_obstacle")# Test:
    println("--The previous collision obstacle is never the same as the")
    println("  current in a closed sinai billiard.")
    println("--The `distance` after propagation is not big.")
  end
  ttotal = 10000.0
  bt = billiard_sinai()

  for ω in [0.0, 0.002, -0.8]
    printinfo && println("...for ω=$ω")

    for j in 1:partnum
      p = randominside(bt, ω)
      d = distance(p, bt) #initial distance
      prev_pos = p.pos
      prev_vel = p.vel
      new_pos = p.pos
      new_vel = p.vel
      colobst_idx::Int = 99
      prev_obst_idx::Int = 99
      tcount::Float64 = 0.0
      colnumber = 0

      while tcount < ttotal
        tmin::Float64 = Inf

        for i in eachindex(bt)
          tcol::Float64 = collisiontime(p, bt[i])
          # Set minimum time:
          if tcol < tmin
            tmin = tcol
            colobst_idx = i
          end
        end#obstacle loop

        if colobst_idx == prev_obst_idx
          if ω==0
            println("Collision with obstacle: $(bt[colobst_idx].name)")
            println("collision time = $tmin")
            println("init. distance = $d")
            println("current pos = $(new_pos)")
            println("current vel = $(new_vel)")
            println("previus pos = $(prev_pos)")
            println("previus vel = $(prev_vel)")
            println("Collision number: $colnumber")
            error("Previuus obstacle was same as current for straight prop.")
          else
            if tmin<1e-6
              println("Collision with obstacle: $(bt[colobst_idx].name)")
              println("collision time = $tmin")
              println("init. distance = $d")
              println("current pos = $(new_pos)")
              println("current vel = $(new_vel)")
              println("previus pos = $(prev_pos)")
              println("previus vel = $(prev_vel)")
              println("Collision number: $colnumber")
              error("Previuus obstacle was same as current for straight prop.")
            end
          end
        end

        propagate!(p, tmin)
        dis = distance(p, bt[colobst_idx])
        if abs(dis) >= 1e-10
          println("Collision with obstacle: $(bt[colobst_idx].name)")
          println("collision time = $tmin")
          println("current pos = $(new_pos)")
          println("current vel = $(new_vel)")
          println("previus pos = $(prev_pos)")
          println("previus vel = $(prev_vel)")
          println("Collision number: $colnumber")
          println("distance after propagation: $dis")
          error("Too large distance after propagation...")
        end
        ### CHECK DISTANCE HERE
        resolvecollision!(p, bt[colobst_idx])
        tcount += tmin
        prev_obst_idx = colobst_idx
        prev_pos = new_pos
        prev_vel = new_vel
        new_pos=p.pos
        new_vel=p.vel
        colnumber += 1

      end#time loop
    end#particle loop
  end#omega loop
  return true
end#test
```

you can set `abs(dis) >= 1e-10` line to even bigger, and will still find some distance that is that big.

**Comment by dapias** [comment]
Has this problem been solved?

**Comment by Datseris** [comment]
Well, yes and no :P 

The thing is, that I have no way to really know what is the accuracy limit. I found that this number `1e-10` was very big, but I do not really know if it is actually big or not. The point is that you can have this happen. 

I wouldn't call it a problem though. Because all the internal structure takes care that you have no particle leakage and all the like, if you seen the source code. There has to be some flexibility that the particle, after propagation, is not super close to the Wall but close enough. I thought `1e-10` was a big distance, but I cannot know for sure.

I will do a *major* update in this package though, where I will make everything parametrically typed. Then I will simply set a global tolerance level of `sqrt(eps(T))`. Meaning that if the user chooses `Float64` everything below 1e-8 will be acceptable. If the user wants something crazy like below `1e-16` he will have to use BigFloats.

**Comment by dpsanders** [comment]
Could this be due to the fact that solving quadratic equations can be numerically badly behaved? Don't know a good reference off the top of my head (maybe Burden & Faires?) but see e.g.

https://people.csail.mit.edu/bkph/articles/Quadratics.pdf

for a summary.

**Comment by Datseris** [comment]
Hm, this could be something that is true. This doesn't matter for straight propagation, because I always get only one of the roots, but for magnetic propagation has major impact. I have to look into it probably.

For the distance until a circular obstacle though, I simply use the formula:
`distance(p::AbstractParticle, d::Circular) = norm(p.pos - d.c) - d.r`
is this a bad idea? :D

**Comment by dpsanders** [comment]
Subtracting two small numbers is always a bad idea (but it's not clear to me if this is what is happening).

**Comment by Datseris** [comment]
Yes this exactly what is happening :( bouhou. Well, fortunately this happens *after* I have propagated the particle, where I simply check how close it is to the Obstacle it is supposed to collide with. So maybe it is not a big deal after all? 

(I mean that these checks that I talk about in this issue, have little bearing on the actual working of the package)

**Comment by dpsanders** [comment]
I wonder if there is a way of rewriting it so that this doesn't happen.

**Comment by Datseris** [comment]
Solved with release [v.1.4.0](https://github.com/JuliaDynamics/DynamicalBilliards.jl/releases/tag/v1.4.0), Now users can choose the level of accuracy the want.
