### ISSUE TITLE
Direct computation of evolution timeseries

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalBilliards.jl#162]
Doing `construct(evolve(p, bd, t)...)` has the disadvantage that it allocates a lot of unecessary stuff inbetween. It is better to define one extra new function that directly outputs the timeseries of positions and velocities and time.

To avoid code repetition, it is best to define also an internal function `extrapolate(p, prevpos, t)` that given the particle, the previous position and the time to go to the new position (which is `p.pos`), it extrapolates in between the position and velocity timeseries (notice that for `Particle` this is trivial: it just returns velocity and position).

From a tutorial I have written, that only extrapolates position and not velocity, this looks like:
```
    while c < n
        prevpos = p.pos; prevvel = p.vel
        i, ct, cp = bounce!(p, bd)
        xs, ys = extrapolate(p, prevpos, prevvel, ct)
        push!(t, ct)
        append!(xt, xs)
        append!(yt, ys)
        c += 1
    end

extrapolate(p::Particle, prevpos, prevvel, ct) = p.pos

function extrapolate(p::MagneticParticle, prevpos, prevvel, t)
    φ0 = atan(prevvel[2], prevvel[1])
    s0, c0 = sincos(φ0)
    x0 = prevpos[1]; y0 = prevpos[2]
    xt = [x0]; yt = [y0]; ω = p.ω
    tvec = 0.0:0.01:t
    for td in tvec
        s, c = sincos(p.ω*td + φ0)
        push!(xt, s/ω + x0 - s0/ω)
        push!(yt, -c/ω + y0 + c0/ω) #vx0 is cos(φ0)
    end
    return xt, yt
end
```

**Comment by lhupe** [comment]
@Datseris I could implement this as part of my new animation code, I would need some sort of function like that anyway. However, I have some suggestions: 
The user should be able to specify the time vector for both `MagneticParticle` and `Particle`. This would be extremly helpful for making the new animation stuff more elegant.
This `tvec` argument could be optional, with default values that restore the behaviour from your example (the default `tvec` for `Particles` could just be `ct`). 

What do you think?

**Comment by Datseris** [comment]
> The user should be able to specify the time vector for both MagneticParticle and Particle. This would be extremly helpful for making the new animation stuff more elegant.

I am sure that by "time vector" you mean just `dt`, right? Otherwise, what time vector? 

Yes being able to specify this for both is best. `dt` will be the amount you plot in one step.

Or I have misunderstood?
