### ISSUE TITLE
timeseries! is clearly wrong for default dt=Inf ! ! ! 

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalBilliards.jl#189]
# Issue Description
The function `timeseries` has a huge problem for the default behavior of straight propagation, which is `dt = Inf`. Instead of returning the actual timevector, it returns something that makes no sense.

```julia
bd = billiard_sinai()
p = Particle(0.1, 0.1, 0.1)
t = timeseries(p, bd, 10)[5]
```
```
11-element Array{Float64,1}:
 0.0
 0.9045188265604098
 1.0050209184004553
 0.324989618047841
 0.324650710697295
 1.0048594972898988
 1.0048594972898988
 0.9576474107445281
 0.04721208654537084
 1.0048594972898988
 1.0048594972898988
```
which is spectacularly wrong, since for any `i` it should hold `t[i] < t[i+1]`. Not only that, but the last two elements are the same!!!

If one uses a `dt` smaller than the collision time it works:
```julia
julia> t = timeseries(p, bd, 10; dt = 0.01)[end]
764-element Array{Float64,1}:
 0.0
 0.01
 0.02
 0.03
 0.04
 0.05
 0.06
 0.07
 0.08
 0.09
 0.1
 0.11
 0.12
 0.13
 0.14
 ⋮
 7.448618062865596
 7.458618062865596
 7.468618062865596
 7.478618062865596
 7.488618062865596
 7.498618062865596
 7.508618062865596
 7.518618062865596
 7.528618062865596
 7.538618062865596
 7.548618062865596
 7.558618062865596
 7.568618062865596
 7.578618062865596
 7.583477560155495
```

# Expected Behavior
The tvector should be the cumulative collision times instead of some random stuff.

@lhupe you have done the newest implementation of `timeseries`. Do you know where this stems from?

**Comment by lhupe** [comment]
@Datseris I think I know what the problem is. The plots produced by 
```julia
bd = billiard_sinai()
p = Particle(0.1, 0.1, 0.1)
x,y,vx,vy,t = timeseries(p, bd, 10, dt = 0.01)
plot(t, x)
```
and 
```julia
bd = billiard_sinai()
p = Particle(0.1, 0.1, 0.1)
x,y,vx,vy,t = timeseries(p, bd, 10)
plot(cumsum(t), x)
```
are identical, so for some reason the latter version returns the times in between the collisions instead of the actual time vector.

**Comment by lhupe** [comment]
Turns out this bug was literally just one line of code, so I fixed it.
