### ISSUE TITLE
bdplot not defined

### ISSUE THREAD

**Issue by Flausi** [JuliaDynamics/DynamicalBilliards.jl#205]
Hello I have a problem with the new visualization with Makie. I tried to get the simple examples from the documentation ([link](https://juliadynamics.github.io/DynamicalBilliards.jl/stable/billiards_visualizations/)) to work. Unfortunately I always get the following error message:

`ERROR: LoadError: UndefVarError: bdplot not defined`

The code looks like this.

```
using DynamicalBilliards, InteractiveDynamics, CairoMakie

bd = billiard_hexagonal_sinai()
p1 = randominside(bd)
p2 = randominside(bd, 1.0)
colors = [:red, JULIADYNAMICS_COLORS[1]]
markers = [:circle, :rect]
fig, ax = bdplot(bd)
for (p, c) in zip([p1, p2], colors)
    x, y = DynamicalBilliards.timeseries!(p, bd, 20)
    lines!(ax, x, y; color = c)
end
bdplot!(ax, [p1, p2]; colors, particle_size = 10, marker = markers)
fig
```

I would be happy if someone can help me. My packages have the following versions: 
DynamicalBilliards v4.0.0 ; InteractiveDynamics v0.18.1 ; CairoMakie v0.6.4.

**Comment by Datseris** [comment]
> InteractiveDynamics v0.18.1  

You need version 0.20. Ah, damn, that is not mentioned in the docs, i'll keep it as todo.

**Comment by Flausi** [comment]
Hello, oh yes that's right. AbstractPlotting.jl prevented the packages from updating for some reason. Thanks for the answer ;)
