### ISSUE TITLE
Update lyapunovs for new version

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalBilliards.jl#28]
I have made major changes in the way this package work. I don't remember how fast it was before, but it certainly is fast now. And very precise as well, with the user being able to control the precision!

In the section https://juliadynamics.github.io/DynamicalBilliards.jl/latest/physics/#numerical-precision I am describing how this process works.

As far as the lyapunov exponents are concerned, the functions that are introduced/changed are:

1. `timeprec(T)` at https://github.com/JuliaDynamics/DynamicalBilliards.jl/blob/master/src/Propagation.jl#L11
2. `specular` at https://github.com/JuliaDynamics/DynamicalBilliards.jl/blob/master/src/Propagation.jl#L37 (which is made to depend on parametric types)
3. `resolvecollision` at https://github.com/JuliaDynamics/DynamicalBilliards.jl/blob/master/src/Propagation.jl#L77 now simply decides whether to do specular reflection or not
4. **Most importantly**, the function `relocate!` at https://github.com/JuliaDynamics/DynamicalBilliards.jl/blob/master/src/Propagation.jl#L87 has been fundamentally changed.
5. Due to the above change, the way `propagate!` works and is used in `evolve!()` is different now. See https://github.com/JuliaDynamics/DynamicalBilliards.jl/blob/master/src/Propagation.jl#L162 and https://github.com/JuliaDynamics/DynamicalBilliards.jl/blob/master/src/Propagation.jl#L321

@dapias Since you have contributed the Lyapunov exponents, would you also like to update your functions so that they work with this new and major change to the package? If you do that, the `lyapunovspectrum` will be included in the 1.5.0 release version!

Also, notice that the tests have been updated. I have created an entirely new function that takes care of the lyapunov exponents: https://github.com/JuliaDynamics/DynamicalBilliards.jl/blob/master/test/various.jl#L61 and you don't have to do anything about that (when the functions in the `LyapunovSpectrum.jl` file work properly).

**Comment by dapias** [comment]
Sure. I will take care of it by updating the functions

**Comment by dapias** [comment]
Please check this ba26f66880a38686696b6eb603f761b767d51e9c

**Comment by Datseris** [comment]
Wait I am super confused now.

Where did this commit happen? I cannot see it anywhere besides clicking on this link. When I go to the master branch, the latest commit was from me 6 days ago...

Also, I think it is a good idea for both of us to try to work with branches exclusively for major changes, since now this is a collaborative project! (How cool is that! I would never have imagined it)

The branches have many advantages. First of all noone can mess with your respective branch, which you can also keep local, without pushing it to a remote. Also, it is much more convenient to start a new discussion on a Pull Request, than it is on an Issue. Finally, it will make conflictions easier to resolve!

I am also getting used to branches. I did the Parametric Types change with a branch, but then I messed up and did regular commits. But from now on branches all the way through!

**Comment by dapias** [comment]
So, I created a new branch on the main repository with  these changes. Do you want me to implement the Arrays as Static Arrays before trying a pull request?

**Comment by Datseris** [comment]
No, you don't have to stress about staticarrays. I think it may make the computations faster, but this is only for your benefits!

**Comment by dapias** [comment]
I decided to use StaticArrays. A better performance is always a good thing... Maybe version 1.5.0 is ready! Nice work about the numerical precision. The code looks better now and it is more simple to understand.

**Comment by Datseris** [comment]
Awesome! 

I just want to try and see if I can fix some bugs today, otherwise I Will release 1.5.0 with the Lyapunovs!

**Comment by Datseris** [comment]
@dapias woohoo, v1.5.0 is tagged!
