### ISSUE TITLE
use SMatrix and access with SVector{Int} in lyapunovs

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalBilliards.jl#63]
I am quite sure it will be much faster to use static vectors and not mutable static vectors all over lyapunovs.

Also, there is no need for mutable matrix, because you can simply `vcat` or `hcat` static vectors and it is super efficient, and you simply use static matrices.

Also, accessing static matrices with ranges like `1:2` is bad for performance. They should be accessed with static vectors of indices, like `SVector(1, 2)` instead.

**Comment by ChrisRackauckas** [comment]
This may change on v0.7 since literals are handled well I think?

**Comment by Datseris** [comment]
> This may change on v0.7 since literals are handled well I think?

@ChrisRackauckas Thanks for letting me know. I am actually thinking of switching development for the Billiards v2.0 to Julia 0.7. Do you think its a a stable enough point to do this?

**Comment by ChrisRackauckas** [comment]
It's mostly dependent on your dependencies, and your dependency list looks small enough I'd give it a try.

**Comment by Datseris** [comment]
Lyapunovs are now 25 times faster due to changing the internal algorithm
