### ISSUE TITLE
make cyclotron center and radius field of particle

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalBilliards.jl#70]
The function `cyclotron` is computed at all `collisiontime` functions. This means that the *same* computation is done like 5 times. We should make both center and radius fields of `MagneticParticle` and instead have the functions `resolvecollision` to change the fields when they e.g. reflect the particle.

**Comment by Datseris** [comment]
Division is *much* more expensive than multiplication. In a very big amount of code we do `/ω`. This is expensive and this change will bring big performance boosts!

**Comment by ChrisRackauckas** [comment]
Well, the compiler does the quite a bit, especially if you `@fastmath`.

**Comment by Datseris** [comment]
unfortunately I never do this `@fastmath` because I got knowledge of what it does and no time to check how much stuff it could break. Because here in the billiards package it always falls done to machine precision...

maybe it is worth taking a look
