### ISSUE TITLE
Create function `boundarymap_portion` 

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/DynamicalBilliards.jl#99]
Lukas, after you are done with your task, we should put this function here. Seems super useful in general. The way I imagine it working is:
```julia
boundarymap_portion(p, bt, t, δ)
```
here is what it should do:

1. Calculate total arglength. We know sin(φ) goes from -1 to 1.
2. "Partition" the phase-space into boxes of size δ, *mentally*, don't create matrix.
3. Start evolving particle bounce by bounce. After each bounce add an entry to the phase-space box the particle is, in boundary map coordinates. Use the dictionary approach from chaostools.
4. After evolution compute the ratio of dictionary entries to total possible entries.
5. return the ratio and the dictionary as well. Can be very useful!

**Comment by lhupe** [comment]
Do you have any preferences on where to put this function (`poincaresos.jl` or maybe a seperate file)?

**Comment by Datseris** [comment]
`poincaresos.jl` is fine
